### ISSUE TITLE
Error (void-variable for)

### ISSUE THREAD

**Issue by PinkFLoyd92** [ScottyB/ac-js2#24]
My setup works pretty good except for this little detail, this keeps showing up, this just happens with ac-js2. Anyone knows how to fix this?

![image](https://cloud.githubusercontent.com/assets/8844096/23613157/3ca9f4ac-024c-11e7-832d-7179f79b8fef.png)

Here is the stacktrace...
![image](https://cloud.githubusercontent.com/assets/8844096/23613212/729cb75c-024c-11e7-9061-c50d93ea865f.png)

**Comment by kgritesh** [comment]
Hi @PinkFLoyd92 i am facing the same error were you able to solve this

**Comment by kgritesh** [comment]
This issue is caused by missing explicit require to `cl`, and your Emacs set-up probably doesn't include anything else which loads that library. I was able to solve it by `M-x load-library RET cl RET`. You should also put `(require 'cl)` in your emacs start-up file. Taken from responses to this [issue](https://github.com/purcell/flymake-ruby/issues/4)

**Comment by PinkFLoyd92** [comment]
Thanks, that fixed the problem for me!
